[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# words that should not be corrected
Damon = "Damon"
ND = "ND"

[files]
extend-exclude = [
    "*.bib",
    "*.html",
    "*.js",
    "*.csl",
    "*.css",
    "*.csv",
]
